spring.application.name=pietapa9
spring.datasource.url=jdbc:mysql://localhost:3306/pi_etapa9
spring.datasource.username=root
spring.datasource.password=35242292

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=12345